### PR TITLE
Add default enum for EventType.

### PR DESCRIPTION
**Pull request by hlieberman**
Add a default enum for EventType (since Unknown is already a thing).

### CODE REVIEW

**Comment by dcuddeback** [comment]
@hlieberman Just curious. What's the use case for having a default value on the `EventType` enum?

**Comment by hlieberman** [comment]
I'm having trouble with the scoping rules around using match. The compiler
won't let me pass the event out of the scope that the monitor is in,
probably because there's a reference to it in there somewhere. So I'm just
using a struct to pass information in and out of the function... and I'd
like to use #[derive(Default)] on it.

**Comment by dcuddeback** [comment]
@hlieberman Makes sense. Maybe deriving Copy and Clone for EventType would help, too.

**Comment by dcuddeback** [comment]
@hlieberman I pushed up a commit that derives Copy, Clone, PartialEq, and Eq for EventType. That's something I overlooked before, but it should make working with EventType a little nicer.

**Comment by dcuddeback** [comment]
@hlieberman I think I found the source of your scope problems. The MonitorEvent was picking up the lifetime of the Monitor, which is unnecessarily restrictive because it only holds a reference to the context. I pushed up a fix that makes the lifetime explicit: https://github.com/dcuddeback/libudev-rs/commit/470f6c0950c0e9097130801a4f0235adf98818e1

**Pull request merged**
